### PR TITLE
Add print method and extraction functions

### LINKED ISSUE #28: Create functions for extracting data from `wesp_site`
- [x] `print.wesp_site()`
- [x] `get_responses()` - data.frame of all questions and derived values
- [x] `get_indicator_scores()` - a data.frame of scores

### PR DESCRIPTION
**Pull request by ateucher**
Closes #28 

Adds:

- a `print()` method which shows the main attributes of a `wesp_site` object.
- `get_indicator_scores()` which returns the indicator scores as a data.frame
- `get_responses()` which returns the responses as a data.frame
- `get_derived_values()` which returns the derived values as a data.frame

Example usage:

``` r
library(wespr)

site <- load_wesp_data(system.file("input_data/wetFlat.csv", package = "wespr")) |> 
  as.wesp_site()
#> Warning: Question F25 does not appear to have been filled out.
#> Warning: Question F41 does not appear to have been filled out.
#> Warning: Question F43 does not appear to have been filled out.
#> Warning: Question F44 does not appear to have been filled out.
#> Warning: Question F59 does not appear to have been filled out.
#> Warning: Question OF28 does not appear to have been filled out.

site
#> A wesp_site object
#> 
#> Site:  site_1 
#> 
#> Incomplete Questions:  F25, F41, F43, F44, F59, OF28 
#> 
#> Derived values:
#>   *  AllWater = 0
#>   *  NeverWater = 0
#>   *  NoSeasonal = 0
#>   *  NoPersis = 0
#>   *  TempWet = 0
#>   *  AllPermW = 0
#>   *  HiFlucW = 0
#>   *  TooShallow = 0
#>   *  NoPond = 0
#>   *  NoDeepPonded = 0
#>   *  NoOW = 0
#>   *  NoOutletX = 0
#>   *  NoOutlet = 1
#>   *  Inflow = 0
#>   *  Disturb = 1
#>   *  FishFound = 0
#>   *  Moose = 0
#>   *  Beaver = 1
#>   *  Muskrat = 0
#>   *  Bear = 0
#>   *  Caribou = 0
#>   *  NoCA = 0
#>   *  Fishless = 0
#>   *  GDeco = 0
#>   *  CMeco = 1
#>   *  SIMeco = 0
#>   *  BPeco = 0
#>   *  TPeco = 0
#>   *  OutMap = 0
#>   *  S1_sum = 2
#>   *  S1_subscore = 0.17
#>   *  S2_sum = 0
#>   *  S2_subscore = 0
#>   *  S3_sum = 0
#>   *  S3_subscore = 0
#>   *  S4_sum = 5
#>   *  S4_subscore = 0.42
#>   *  S5_sum = 0
#>   *  S5_subscore = 0
#>   *  S6_sum = 0
#>   *  S6_subscore = 0
#> 
#> Indicators:
#> All indicators are NULL. Run `calc_indicators()` to calculate them.

site <- calc_indicators(site)

site
#> A wesp_site object
#> 
#> Site:  site_1 
#> 
#> Incomplete Questions:  F25, F41, F43, F44, F59, OF28 
#> 
#> Derived values:
#>   *  AllWater = 0
#>   *  NeverWater = 0
#>   *  NoSeasonal = 0
#>   *  NoPersis = 0
#>   *  TempWet = 0
#>   *  AllPermW = 0
#>   *  HiFlucW = 0
#>   *  TooShallow = 0
#>   *  NoPond = 0
#>   *  NoDeepPonded = 0
#>   *  NoOW = 0
#>   *  NoOutletX = 0
#>   *  NoOutlet = 1
#>   *  Inflow = 0
#>   *  Disturb = 1
#>   *  FishFound = 0
#>   *  Moose = 0
#>   *  Beaver = 1
#>   *  Muskrat = 0
#>   *  Bear = 0
#>   *  Caribou = 0
#>   *  NoCA = 0
#>   *  Fishless = 0
#>   *  GDeco = 0
#>   *  CMeco = 1
#>   *  SIMeco = 0
#>   *  BPeco = 0
#>   *  TPeco = 0
#>   *  OutMap = 0
#>   *  S1_sum = 2
#>   *  S1_subscore = 0.17
#>   *  S2_sum = 0
#>   *  S2_subscore = 0
#>   *  S3_sum = 0
#>   *  S3_subscore = 0
#>   *  S4_sum = 5
#>   *  S4_subscore = 0.42
#>   *  S5_sum = 0
#>   *  S5_subscore = 0
#>   *  S6_sum = 0
#>   *  S6_subscore = 0
#> 
#> Indicators:
#>   * WS:  
#>     - fun: 7.02 
#>     - ben: 5.89 
#>   * SR:  
#>     - fun: 4.12 
#>     - ben: 3.67 
#>   * PR:  
#>     - fun:  
#>     - ben:  
#>   * CS:  
#>     - fun: 8.72 
#>   * FR:  
#>     - fun:  
#>     - ben:  
#>   * SENS:  
#>     - fun:  
#>   * STR:  
#>     - fun:  
#>   * NR:  
#>     - fun:  
#>     - ben:  
#>   * AP:  
#>     - fun:  
#>     - ben:  
#>   * PD:  
#>     - fun:  
#>     - ben:  
#>   * KMH:  
#>     - fun:  
#>     - ben:  
#>   * WB:  
#>     - fun:  
#>     - ben:  
#>   * POL:  
#>     - fun:  
#>     - ben:  
#>   * RSB:  
#>     - fun:  
#>     - ben:  
#>   * OE:  
#>     - fun:  
#>   * AM:  
#>     - fun:  
#>     - ben:  
#>   * FH:  
#>     - fun:  
#>     - ben:  
#>   * SFTS:  
#>     - fun:  
#>     - ben:  
#>   * CRI:  
#>     - ben:  
#> 
#> * Retrieve indicator scores with `get_indicator_scores()`

get_indicator_scores(site)
#> # A tibble: 3 × 4
#>   site   indicator   fun   ben
#>   <chr>  <chr>     <dbl> <dbl>
#> 1 site_1 WS         7.02  5.89
#> 2 site_1 SR         4.12  3.67
#> 3 site_1 CS         8.72 NA

get_responses(site)
#> # A tibble: 488 × 4
#>    no    question                           response_no value       
#>    <chr> <chr>                              <chr>       <named list>
#>  1 F1    Vegetation Height & Form Diversity F1_1        <dbl [1]>   
#>  2 F1    Vegetation Height & Form Diversity F1_2        <dbl [1]>   
#>  3 F1    Vegetation Height & Form Diversity F1_3        <dbl [1]>   
#>  4 F1    Vegetation Height & Form Diversity F1_4        <dbl [1]>   
#>  5 F1    Vegetation Height & Form Diversity F1_5        <dbl [1]>   
#>  6 F1    Vegetation Height & Form Diversity F1_6        <dbl [1]>   
#>  7 F10   Dense Moss Extent                  F10_1       <dbl [1]>   
#>  8 F10   Dense Moss Extent                  F10_2       <dbl [1]>   
#>  9 F10   Dense Moss Extent                  F10_3       <dbl [1]>   
#> 10 F10   Dense Moss Extent                  F10_4       <dbl [1]>   
#> # ℹ 478 more rows

get_derived_values(site)
#> # A tibble: 41 × 2
#>    name         value
#>    <chr>        <dbl>
#>  1 AllWater         0
#>  2 NeverWater       0
#>  3 NoSeasonal       0
#>  4 NoPersis         0
#>  5 TempWet          0
#>  6 AllPermW         0
#>  7 HiFlucW          0
#>  8 TooShallow       0
#>  9 NoPond           0
#> 10 NoDeepPonded     0
#> # ℹ 31 more rows
```

<sup>Created on 2023-12-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by ateucher** [comment]
@gcperk I think this is ready for your review. One thing I am struggling with is in `get_responses()`, there is the one response (`OF29`, topographic position) that is a character, meaning that we can't have the `value` column be numeric. Currently it's a list column, but that is a bit unwieldy. The other option is to have two columns `value_numeric` with all of the responses except `OF29` (which would be NA), and `value_category` with all `NA` except for `OF29`. This is kind of unsatisfying as well. Any ideas?

**Review by gcperk — APPROVED** [review]

**Comment by gcperk** [comment]
Those functions are awesome thanks @ateucher. I was thinking about the problem with the letter values (topographic position). I think a nice fix would be to add that to the conversion between the survey 123 and get it into the "wetflat" file. I will add an issue (or update this?).

**Comment by ateucher** [comment]
Thanks @gcperk - that's a good idea... or I can use a lookup in the package, since they seem to be used the same way in all indicators:

T=5, L=4, D=3, M=2, [U,C,F]=0

**Comment by ateucher** [comment]
I'll merge this and address it separately. New issue: #35

**Pull request merged**
